const readyMedia = ({
  id,
  title,
  context,
  description,
  requiredContext,
  alt,
  caption,
  replaces = [],
  placements = [],
  desktopWidth = 1600,
  desktopHeight = 1000,
  mobileWidth = 390,
  mobileHeight = 844,
  capturedOn = '2026-09-18',
}) => Object.freeze({
  id,
  title,
  status: 'ready',
  context,
  description,
  requiredContext,
  replaces,
  placements,
  desktop: Object.freeze({
    src: `/marketing/current/${id}.webp`,
    width: desktopWidth,
    height: desktopHeight,
  }),
  mobile: Object.freeze({
    src: `/marketing/current/${id}-mobile.webp`,
    width: mobileWidth,
    height: mobileHeight,
  }),
  alt,
  caption,
  capturedOn,
})

export const productMedia = Object.freeze({
  overview: readyMedia({
    id: 'eod-overview-spy-2w',
    title: 'EOD Overview',
    context: 'Recorded SPY example · EOD · 2W',
    description: 'Q Score components, summary metrics, and option distributions in the dashboard.',
    requiredContext: ['Symbol', 'EOD mode', '2W scope', 'Data date', 'Q Score date'],
    alt: 'GEX Options EOD Overview for SPY with the 2W expiry scope, Q-Score summary, component scores, and signal dates.',
    caption: 'Recorded SPY EOD Overview with the 2W expiry scope, September 2026 data dates, and Q-Score components visible.',
    replaces: ['qscore.png', 'oiAndVolChart.png'],
    placements: ['features-eod-overview'],
    desktopWidth: 1428,
    desktopHeight: 992,
    mobileHeight: 270,
    capturedOn: '2026-09-19',
  }),
  positioning: readyMedia({
    id: 'eod-positioning-spy',
    title: 'Dealer positioning',
    context: 'Recorded SPY example · EOD · fixed 2W gamma context',
    description: 'Net dealer delta, gamma regime, regime strength, and signed exposure by expiry.',
    requiredContext: ['DEX date', 'Gamma scope', 'Gamma regime', 'Signed expiry exposure'],
    alt: 'GEX Options dealer positioning panel showing negative net dealer delta, negative gamma, regime strength, and signed DEX by expiry.',
    caption: 'Recorded SPY dealer-positioning example with the dated DEX reading, fixed 2W gamma context, and signed exposure by expiry.',
    replaces: ['dex.png'],
    placements: ['home-dealer-positioning', 'features-eod-positioning'],
    desktopWidth: 840,
    desktopHeight: 979,
    mobileHeight: 454,
    capturedOn: '2026-09-19',
  }),
  expiryPressure: readyMedia({
    id: 'eod-expiry-pressure-spy',
    title: 'Expiry pressure',
    context: 'Recorded SPY example · EOD · next three trading days',
    description: 'Headline pin score, max pain, cluster readings, and dates.',
    requiredContext: ['Data date', 'Pin score', 'Selected expiry', 'Max pain', 'Cluster readings'],
    alt: 'GEX Options expiry pressure panel with a headline pin score, selected expiry, max pain, and ranked cluster readings.',
    caption: 'Recorded SPY expiry-pressure example covering the next three trading days with pin scores, max pain, and cluster evidence.',
    replaces: ['pin.png'],
    placements: ['features-eod-positioning'],
    desktopWidth: 531,
    desktopHeight: 1073,
    mobileHeight: 788,
    capturedOn: '2026-09-19',
  }),
  skewPricing: readyMedia({
    id: 'eod-skew-pricing-spy',
    title: 'Put-versus-call pricing',
    context: 'Recorded SPY example · EOD · 1W target',
    description: '25-delta put and call IV, skew, daily change, curvature, and rolling history.',
    requiredContext: ['Target horizon', 'Selected expiry', 'Data date', 'Skew units', 'History coverage'],
    alt: 'GEX Options put-versus-call pricing view showing 25-delta implied volatility, skew, daily skew change, and rolling history.',
    caption: 'Recorded SPY 1W pricing example with 25-delta put and call IV, 5.5 percentage-point skew, and 30-day history visible.',
    replaces: ['ivSkew.png'],
    placements: ['features-hero', 'home-put-call-pricing', 'features-eod-positioning'],
    desktopWidth: 1502,
    desktopHeight: 1007,
    mobileHeight: 262,
    capturedOn: '2026-09-19',
  }),
  volatility: readyMedia({
    id: 'eod-volatility-spy',
    title: 'Term structure',
    context: 'Recorded SPY example · EOD · 19 expiries',
    description: 'ATM implied volatility from the front expiry through the back of the returned curve.',
    requiredContext: ['Data date', 'Expiry count', 'IV units', 'Selected expiry'],
    alt: 'GEX Options term-structure panel showing a contango regime, front implied volatility, and the expiry curve.',
    caption: 'Recorded SPY term-structure example with 19 usable expiry readings, the selected front expiry, and IV units visible.',
    replaces: ['term.png'],
    placements: ['features-eod-volatility'],
    desktopWidth: 659,
    desktopHeight: 791,
    mobileHeight: 468,
    capturedOn: '2026-09-19',
  }),
  volatilityVrp: readyMedia({
    id: 'eod-volatility-vrp-spy',
    title: 'Variance risk premium',
    context: 'Recorded SPY example · EOD · one-month IV versus RV(20)',
    description: 'Implied volatility, realized volatility, premium, and historical position.',
    requiredContext: ['Data date', 'Selected expiry', 'IV', 'RV', 'Historical position'],
    alt: 'GEX Options variance-risk-premium panel comparing one-month implied volatility with realized volatility and historical position.',
    caption: 'Recorded SPY variance-risk-premium example with IV, RV(20), percentage-point premium, and comparison dates.',
    replaces: ['risk.png'],
    placements: ['features-eod-volatility'],
    desktopWidth: 654,
    desktopHeight: 791,
    mobileHeight: 472,
    capturedOn: '2026-09-19',
  }),
  volatilitySeasonality: readyMedia({
    id: 'eod-volatility-seasonality-spy',
    title: 'Five-session seasonality',
    context: 'Recorded SPY example · EOD · five forward sessions',
    description: 'Historical average forward returns with daily direction and sample context.',
    requiredContext: ['Data date', 'Regime', 'Forward-return path', 'Sample context'],
    alt: 'GEX Options five-session seasonality panel with cumulative return, regime, historical position, and daily forward-return bars.',
    caption: 'Recorded SPY seasonality example showing the five-session path, neutral regime, and the historical sample window.',
    replaces: ['seasonality.png'],
    placements: ['features-eod-volatility'],
    desktopWidth: 1332,
    desktopHeight: 700,
    mobileHeight: 204,
    capturedOn: '2026-09-19',
  }),
  unusualActivity: readyMedia({
    id: 'eod-ua-spy',
    title: 'EOD Unusual Activity',
    context: 'Recorded example · EOD · selected expiry scope',
    description: 'Applied filters, ranking, result detail, and contract details for a closer look.',
    requiredContext: ['Symbol', 'Data date', 'Applied filters', 'Result count', 'Effective premium floor'],
    alt: 'GEX Options SPY Unusual Activity view with applied filters, a 14-result data summary, and selected signal details.',
    caption: 'Recorded SPY Unusual Activity view with the September 11 data set, applied screening thresholds, returned count, and selected contract evidence.',
    replaces: ['ua.png'],
    placements: ['features-eod-unusual-activity'],
  }),
  unusualActivityResults: readyMedia({
    id: 'eod-ua-results-spy',
    title: 'Unusual Activity results',
    context: 'Recorded SPY example · EOD · returned signal set',
    description: 'Headline signal, selected contract evidence, and sortable returned results.',
    requiredContext: ['Symbol', 'Data date', 'Returned signals', 'Selected signal', 'Ranked table'],
    alt: 'GEX Options Unusual Activity results with headline metrics, a selected signal, volume mix, and ranked returned contracts.',
    caption: 'Recorded SPY Unusual Activity result set with the data date, selected signal detail, and ranked returned rows visible.',
    placements: ['features-eod-unusual-activity'],
    desktopWidth: 1367,
    desktopHeight: 1008,
    mobileHeight: 288,
    capturedOn: '2026-09-19',
  }),
  eodStrikes: readyMedia({
    id: 'eod-strikes-spy-2w',
    title: 'EOD Strikes',
    context: 'Recorded SPY example · EOD · 2W',
    description: 'Net GEX and comparison charts with selected strike, units, dates, and included expirations.',
    requiredContext: ['Symbol', '2W scope', 'Data date', 'Included expirations', 'Legend', 'Selected strike'],
    alt: 'GEX Options SPY EOD Strikes view with ten included 2W expirations, Net GEX summaries, and an interactive strike distribution.',
    caption: 'Recorded SPY EOD Strikes view with the 2W scope, September 11 data set, included expirations, selected strike, and signed Net GEX chart.',
    replaces: ['gex.png', 'oiByStrike.png', 'volBYStrike.png'],
    placements: ['home-hero', 'home-gex-levels', 'features-eod-strikes'],
    desktopWidth: 1349,
    desktopHeight: 1171,
    mobileHeight: 338,
    capturedOn: '2026-09-19',
  }),
  eodStrikesVolumeChange: readyMedia({
    id: 'eod-strikes-volume-change-spy',
    title: 'Contract volume change by strike',
    context: 'Recorded SPY example · EOD · daily comparison',
    description: 'Net, call, and put contract-volume changes across the active strike range.',
    requiredContext: ['Symbol', 'Data date', 'Comparison date', 'Units', 'Selected strike'],
    alt: 'GEX Options chart of daily call and put contract-volume changes by strike with selected-strike context.',
    caption: 'Recorded SPY EOD strike comparison showing daily contract-volume changes, activity controls, and the selected strike.',
    replaces: ['volBYStrike.png'],
    placements: ['features-eod-strikes'],
    desktopWidth: 1330,
    desktopHeight: 906,
    mobileHeight: 266,
    capturedOn: '2026-09-19',
  }),
  eodStrikesOiChange: readyMedia({
    id: 'eod-strikes-oi-change-spy',
    title: 'Open-interest change by strike',
    context: 'Recorded SPY example · EOD · daily comparison',
    description: 'Net, call, and put open-interest changes across the active strike range.',
    requiredContext: ['Symbol', 'Data date', 'Comparison date', 'Units', 'Selected strike'],
    alt: 'GEX Options chart of daily call and put open-interest changes by strike with selected-range context.',
    caption: 'Recorded SPY EOD strike comparison showing daily open-interest changes, activity controls, and the selected strike range.',
    replaces: ['oiByStrike.png'],
    placements: ['features-eod-strikes'],
    desktopWidth: 1335,
    desktopHeight: 901,
    mobileHeight: 264,
    capturedOn: '2026-09-19',
  }),
  intradayFlow: readyMedia({
    id: 'intraday-flow-spy',
    title: 'Intraday Live Flow',
    context: 'Recorded SPY session example · session time shown',
    description: 'Session volume, put/call mix, estimated premium, and inspectable strike activity from a recorded session.',
    requiredContext: ['Symbol', 'Trade date', 'Source time', 'Market state', 'Data availability', 'Selected strike'],
    alt: 'GEX Options SPY Intraday Flow view with stored-response status, session volume, put-call mix, estimated premium, and strike inspection.',
    caption: 'Recorded SPY Intraday Flow data for September 11 with response age, session totals, put-call ratio, premium estimate, and selected-strike context visible.',
    replaces: ['liveFlow.png'],
    placements: ['home-intraday-preview', 'features-intraday-flow'],
    desktopWidth: 1364,
    desktopHeight: 1052,
    mobileHeight: 300,
    capturedOn: '2026-09-19',
  }),
  intradayStrikes: readyMedia({
    id: 'intraday-strikes-spy',
    title: 'Intraday Live Strikes',
    context: 'Recorded SPY session example · session time shown',
    description: 'Volume/open-interest, put/call ratio, and estimated premium by strike for a closer look.',
    requiredContext: ['Symbol', 'Trade date', 'Source time', 'Units', 'Selected strike', 'API or derived provenance'],
    alt: 'GEX Options SPY Intraday Strikes view with volume-to-open-interest summaries, selected strike, and ratio chart.',
    caption: 'Recorded SPY Intraday Strikes data with September 11 session context, Vol/OI readings and selected-strike detail.',
    replaces: ['premiumLive.png', 'pcr.png', 'volOiByStrike.png'],
    placements: ['features-intraday-strikes'],
    desktopWidth: 1333,
    desktopHeight: 993,
    mobileHeight: 290,
    capturedOn: '2026-09-20',
  }),
  intradayStrikesPutCall: readyMedia({
    id: 'intraday-strikes-put-call-spy',
    title: 'Put/call volume by strike',
    context: 'Recorded SPY session example · session time shown',
    description: 'Cumulative session put volume divided by cumulative call volume at each strike.',
    requiredContext: ['Symbol', 'Source time', 'Ratio units', 'Coverage', 'Selected strike'],
    alt: 'GEX Options intraday put-call volume ratio by strike with aggregate ratio and selected-range inspection.',
    caption: 'Recorded SPY Intraday Strikes data with put/call ratio units and selected-strike detail visible.',
    replaces: ['pcr.png'],
    placements: ['features-intraday-strikes'],
    desktopWidth: 1336,
    desktopHeight: 973,
    mobileHeight: 284,
    capturedOn: '2026-09-20',
  }),
  intradayStrikesPremium: readyMedia({
    id: 'intraday-strikes-premium-spy',
    title: 'Session premium by strike',
    context: 'Recorded SPY session example · session time shown',
    description: 'Cumulative call and put premium-notional estimates across the active strike range.',
    requiredContext: ['Symbol', 'Source time', 'Dollar units', 'Coverage', 'Selected strike'],
    alt: 'GEX Options intraday session premium estimates by strike with call and put totals and selected-range inspection.',
    caption: 'Recorded SPY Intraday Strikes data with estimated call and put premium and selected range visible.',
    replaces: ['premiumLive.png'],
    placements: ['features-intraday-strikes'],
    desktopWidth: 1333,
    desktopHeight: 979,
    mobileHeight: 286,
    capturedOn: '2026-09-20',
  }),
  watchlist: readyMedia({
    id: 'watchlist-navigation',
    title: 'Watchlist and navigation',
    context: 'Recorded local review account · generic symbols only',
    description: 'Compact symbol selection, search, status context, and routes into the product tools.',
    requiredContext: ['Generic symbols', 'Selected row', 'Search or add path', 'No account identity'],
    alt: 'GEX Options dashboard navigation with a searchable four-symbol watchlist, SPY selected, and the EOD Overview open.',
    caption: 'Recorded watchlist and dashboard navigation example with AAPL, IWM, QQQ, and SPY, including search, selection, and status badges.',
    replaces: ['overviewNav.jpg', 'watchlist.png', 'watchlist-2.png', 'watchlist-3.png', 'watchlist-4.png'],
    placements: ['features-watchlist'],
  }),
  scannerVolume: readyMedia({
    id: 'scanner-volume',
    title: 'Volume Scanner',
    context: 'Recorded market-wide ranking example · ranking window shown',
    description: 'Rank active symbols, compare volume, and open the dashboard in one step.',
    requiredContext: ['Source', 'Source date', 'Ranking scope', 'Returned count', 'Applied controls'],
    alt: 'GEX Options Volume Scanner with Top 200 and five-day controls, four returned symbols, dates, and volume ranking cards.',
    caption: 'Recorded Volume Scanner example with the five-day ranking window, Top 200 scope, four returned symbols, and applied density controls.',
    replaces: ['scanner.png'],
    placements: ['features-scanner-volume'],
  }),
  scannerWalls: readyMedia({
    id: 'scanner-walls',
    title: 'Wall Scanner',
    context: 'Recorded scan example · EOD/intraday views',
    description: 'Find nearby walls with timeframe groups, distance filters, and inspectable levels.',
    requiredContext: ['Applied thresholds', 'Coverage', 'Wall timeframe', 'Source kind', 'Distance units'],
    alt: 'GEX Options Wall Scanner with a one-percent nearest-wall filter, scan results, and call and put wall matches grouped by horizon.',
    caption: 'Recorded Wall Scanner example with the 1% nearest filter, date, 16 matches, distance units, and EOD wall details.',
    replaces: ['terminal_scanner.png'],
    placements: ['home-scanners', 'features-scanner-walls'],
  }),
  calculator: readyMedia({
    id: 'calculator-spy',
    title: 'Options Calculator',
    context: 'Recorded SPY contract example · quote time shown in view',
    description: 'Contract selection, market-data provenance, payoff scenarios, and exact tables in the calculator.',
    requiredContext: ['Symbol', 'Contract identity', 'Quote source and time', 'Pricing input', 'Scenario', 'Breakeven'],
    alt: 'GEX Options Calculator with SPY expirations, contract prices, a selected 765 call, and manual long-call scenario inputs.',
    caption: 'Recorded SPY calculator example with quote time, selected September 25 765 call, mid-price input, manual scenario, and trade summary.',
    replaces: ['calculator.png'],
    placements: ['features-calculator'],
  }),
  calculatorOutcomes: readyMedia({
    id: 'calculator-outcomes-spy',
    title: 'Calculator outcomes',
    context: 'Recorded SPY long-call example · selected scenario',
    description: 'Breakeven, risk, reward, expiration payoff, time path, and exact scenario tables.',
    requiredContext: ['Breakeven', 'Maximum risk', 'Selected scenario', 'P&L at expiration', 'P&L versus time'],
    alt: 'GEX Options calculator outcome view with breakeven, risk, profit potential, expiration payoff, time path, and scenario tables.',
    caption: 'Recorded SPY long-call outcome example with the selected price and day, expiration payoff, time path, and exact tables visible.',
    placements: ['home-calculator-outcomes', 'features-calculator'],
    desktopWidth: 1317,
    desktopHeight: 1151,
    mobileHeight: 340,
    capturedOn: '2026-09-20',
  }),
  aiExport: readyMedia({
    id: 'ai-export',
    title: 'AI Export',
    context: 'Recorded local export setup · generic symbols only',
    description: 'Symbol and indicator scope, export status, recent history, and JSON download workflow.',
    requiredContext: ['Generic symbols', 'Indicator count', 'GEX timeframe scope', 'Status', 'No filenames or account identity'],
    alt: 'GEX Options AI Export setup with four selected symbols, ten indicator groups, a 30-day GEX timeframe, and queue action.',
    caption: 'Recorded AI Export setup with four generic watchlist symbols, ten selected indicator groups, 30D GEX scope, and queued JSON workflow.',
    placements: ['features-ai-export'],
  }),
})

export const homePreviews = Object.freeze([
  {
    id: 'put-call-pricing',
    label: 'Put vs. call pricing',
    title: 'Compare downside and upside volatility pricing',
    summary: 'Use 25-delta put and call IV, skew, daily change, and rolling history to see how protection is priced relative to calls.',
    media: productMedia.skewPricing,
  },
  {
    id: 'dealer-positioning',
    label: 'Dealer positioning',
    title: 'See how dealer exposure changes by expiry',
    summary: 'Read signed DEX beside the gamma regime and its fixed scope, then inspect which expiries carry the largest positive or negative exposure.',
    media: productMedia.positioning,
  },
  {
    id: 'intraday-flow',
    label: 'Intraday flow',
    title: 'See where session activity is building',
    summary: 'Compare call and put volume, premium estimates, and strike activity with the session timing shown in the same view.',
    media: productMedia.intradayFlow,
  },
  {
    id: 'scanner',
    label: 'Wall scanner',
    title: 'Turn the market into a focused list',
    summary: 'Use explicit distance thresholds, timeframe groups, and dates to find nearby call and put walls and open the symbol in context.',
    media: productMedia.scannerWalls,
  },
  {
    id: 'calculator-outcomes',
    label: 'Payoff outcomes',
    title: 'Test the contract before acting',
    summary: 'Inspect breakeven, maximum risk, expiration payoff, and the estimated time path while keeping the selected scenario visible.',
    media: productMedia.calculatorOutcomes,
  },
])

export const featureGroups = Object.freeze([
  {
    id: 'eod-analysis',
    eyebrow: 'After-close context',
    title: 'Five EOD views, each with its real scope',
    description: 'EOD data is prepared after the close. Dates and filters can differ by dataset, so each view keeps its own scope visible.',
    features: [
      {
        id: 'eod-overview',
        title: 'Overview',
        description: 'Read the Q Score components alongside options totals and call/put distributions for the selected EOD timeframe.',
        bullets: ['Four score components with explanations and dates', 'HVL, volume PCR, OI and volume totals and changes', 'Inspectable call/put distributions'],
        media: productMedia.overview,
      },
      {
        id: 'eod-positioning',
        title: 'Positioning',
        description: 'Compare dealer delta, expiry pressure, fixed-scope gamma context, and skew without implying that one filter controls every dataset.',
        bullets: ['Signed DEX by expiry and rankings', 'Expiry clusters, max pain, and pin context', 'Skew, curvature, history, quality, and calculation detail'],
        media: productMedia.positioning,
        previews: [
          {
            id: 'dealer-dex',
            label: 'Dealer DEX',
            title: 'Dealer exposure by expiry',
            summary: 'Net dealer delta, gamma regime, and signed expiry bars show where exposure is concentrated.',
            media: productMedia.positioning,
          },
          {
            id: 'expiry-pressure',
            label: 'Expiry pressure',
            title: 'Pin and cluster context',
            summary: 'Compare the headline pin score with max pain, cluster density, and distance for the selected expiry.',
            media: productMedia.expiryPressure,
          },
          {
            id: 'put-call-pricing',
            label: 'Put vs. call pricing',
            title: 'Skew and its recent path',
            summary: 'See the put-versus-call IV difference, daily change, curvature, and rolling history in percentage points.',
            media: productMedia.skewPricing,
          },
        ],
      },
      {
        id: 'eod-volatility',
        title: 'Volatility',
        description: 'Keep distinct volatility horizons together while retaining each panel’s date and units.',
        bullets: ['All returned term-structure expiries', 'IV, realized volatility, VRP, and z-score', 'Five daily seasonality readings and cumulative result'],
        media: productMedia.volatility,
        previews: [
          {
            id: 'term-structure',
            label: 'Term structure',
            title: 'Implied volatility across expiries',
            summary: 'Read the curve regime, front IV, and back-minus-front spread across every usable expiry.',
            media: productMedia.volatility,
          },
          {
            id: 'variance-risk-premium',
            label: 'Variance premium',
            title: 'Implied versus realized volatility',
            summary: 'Compare one-month implied volatility with RV(20) and its historical standardized position.',
            media: productMedia.volatilityVrp,
          },
          {
            id: 'seasonality',
            label: 'Seasonality',
            title: 'Five-session historical path',
            summary: 'Inspect the average forward-return path, daily direction, regime, and sample context.',
            media: productMedia.volatilitySeasonality,
          },
        ],
      },
      {
        id: 'eod-unusual-activity',
        title: 'Unusual Activity',
        description: 'Apply and review the actual signal filters, then inspect why a returned contract qualified.',
        bullets: ['Applied scope stays separate from draft edits', 'Sortable results with call/put and premium context', 'Complete returned fields remain available'],
        media: productMedia.unusualActivity,
        previews: [
          {
            id: 'filters',
            label: 'Filter setup',
            title: 'Keep applied screening criteria visible',
            summary: 'Review the active scope, thresholds, data date, and result count before interpreting a signal.',
            media: productMedia.unusualActivity,
          },
          {
            id: 'results',
            label: 'Signal results',
            title: 'Inspect why a contract stands out',
            summary: 'Move from the headline reading to selected-signal evidence and the complete ranked result set.',
            media: productMedia.unusualActivityResults,
          },
        ],
      },
      {
        id: 'eod-strikes',
        title: 'Strikes',
        description: 'Inspect Net GEX and dated OI/volume comparisons for the selected EOD expiry timeframe.',
        bullets: ['Net and split call/put GEX views', 'Focus, grouping, zoom reset, and PNG export', 'Full raw strike tables retain every returned row'],
        media: productMedia.eodStrikes,
        previews: [
          {
            id: 'gex-levels',
            label: 'GEX levels',
            title: 'Net gamma exposure by strike',
            summary: 'Find the largest positive and negative gamma concentrations with the selected timeframe and expiries visible.',
            media: productMedia.eodStrikes,
          },
          {
            id: 'volume-change',
            label: 'Volume change',
            title: 'Daily contract-volume change',
            summary: 'Compare net, call, and put volume changes at each strike against the prior trading day.',
            media: productMedia.eodStrikesVolumeChange,
          },
          {
            id: 'oi-change',
            label: 'OI change',
            title: 'Daily open-interest change',
            summary: 'See where call and put open interest increased or decreased across the active strike range.',
            media: productMedia.eodStrikesOiChange,
          },
        ],
      },
    ],
  },
  {
    id: 'intraday-analysis',
    eyebrow: 'During-session updates',
    title: 'Two ways to explore intraday activity',
    description: 'Follow session volume, put/call balance, and strike activity with periodic market-hours updates. Each view shows its update time so you can assess how current the readings are.',
    features: [
      {
        id: 'intraday-live-flow',
        title: 'Live Flow',
        description: 'Review cumulative session volume across returned expiries and inspect call/put activity by strike.',
        bullets: ['Market state, trade date, update time', 'Session volume, put/call ratio, and estimated premium', 'Pointer, keyboard, and touch strike inspection'],
        media: productMedia.intradayFlow,
      },
      {
        id: 'intraday-live-strikes',
        title: 'Live Strikes',
        description: 'Compare three strike views without losing their units, derivation notes, or exact returned data.',
        bullets: ['Volume/open-interest ratio in x', 'Put/call ratio with denominator handling', 'Estimated call and put premium in dollars'],
        media: productMedia.intradayStrikes,
        previews: [
          {
            id: 'volume-open-interest',
            label: 'Volume / OI',
            title: 'Participation relative to open interest',
            summary: 'Spot strikes where current-session volume is elevated relative to the latest EOD open interest.',
            media: productMedia.intradayStrikes,
          },
          {
            id: 'put-call-ratio',
            label: 'Put / call',
            title: 'Session put-versus-call volume',
            summary: 'Compare put and call activity by strike to see which side accounts for more volume.',
            media: productMedia.intradayStrikesPutCall,
          },
          {
            id: 'premium',
            label: 'Premium',
            title: 'Estimated premium by strike',
            summary: 'Inspect cumulative call and put premium-notional estimates across the active strike range.',
            media: productMedia.intradayStrikesPremium,
          },
        ],
      },
    ],
  },
  {
    id: 'scan-and-monitor',
    eyebrow: 'Find and move between symbols',
    title: 'Watchlist and scanners that preserve context',
    description: 'Find active symbols and nearby walls, then open their charts for a closer look.',
    features: [
      {
        id: 'watchlist',
        title: 'Watchlist',
        description: 'Search, add, remove, refresh, and select symbols from a compact list with pin and unusual-activity context.',
        bullets: ['Selected symbol and status remain clear', 'Separate search and add actions', 'Desktop panel and mobile drawer'],
        media: productMedia.watchlist,
      },
      {
        id: 'volume-scanner',
        title: 'Volume Scanner',
        description: 'Compare option volume across the selected ranking window and open any symbol for a closer look.',
        bullets: ['Ranking date, timeframe, and results', 'Compact or comfortable density', 'Dashboard handoff retains symbol and timeframe'],
        media: productMedia.scannerVolume,
      },
      {
        id: 'wall-scanner',
        title: 'Wall Scanner',
        description: 'Find symbols trading near major options walls, compare timeframes, and open the chart behind each result.',
        bullets: ['Percentage and point distance thresholds', 'EOD/intraday context per result', 'Inspectable wall detail and chart controls'],
        media: productMedia.scannerWalls,
      },
    ],
  },
  {
    id: 'plan-and-export',
    eyebrow: 'Define and carry the work forward',
    title: 'Calculator and structured export tools',
    description: 'Model explicit assumptions and export the selected datasets without changing their calculation or scope contracts.',
    features: [
      {
        id: 'options-calculator',
        title: 'Options Calculator',
        description: 'Select a published contract, verify the pricing input, and inspect expiration and time scenarios.',
        bullets: ['Bid, ask, quote time, IV, and DTE', 'Long-call and long-put risk and payoff handling', 'Exact payoff and daily time tables'],
        media: productMedia.calculator,
        previews: [
          {
            id: 'contract-setup',
            label: 'Select contract',
            title: 'Define the contract and assumptions',
            summary: 'Confirm the selected contract, pricing input, quantity, volatility, and underlying scenario.',
            media: productMedia.calculator,
          },
          {
            id: 'outcomes',
            label: 'Inspect outcomes',
            title: 'Read risk, breakeven, and payoff paths',
            summary: 'Compare expiration payoff with the estimated time path and exact scenario tables.',
            media: productMedia.calculatorOutcomes,
          },
        ],
      },
      {
        id: 'ai-export',
        title: 'AI Export',
        description: 'Create a JSON bundle from selected symbols and indicator groups, then keep working while it is prepared.',
        bullets: ['Ten supported indicator groups', 'GEX timeframe applies only to GEX data', 'Queued, running, completed, failed, history, and download states'],
        media: productMedia.aiExport,
      },
    ],
  },
])

export const buildHomeFaqs = trialDays => Object.freeze([
  {
    q: 'What is the difference between EOD and intraday views?',
    a: 'EOD views use completed EOD data for planning and comparison. Intraday views use stored session updates and show the session time and market status in the terminal.',
  },
  {
    q: 'Is intraday data a streaming tick feed?',
    a: 'Intraday views update periodically rather than tick by tick. Track session activity and check the displayed update time for each update.',
  },
  {
    q: 'Which symbols are supported?',
    a: 'Explore supported US-listed optionable stocks and ETFs. Use symbol search and your watchlist to move between charts.',
  },
  {
    q: 'Does one timeframe control every EOD panel?',
    a: 'No. The selected EOD timeframe applies to Overview and Strikes. Positioning, Volatility, and Unusual Activity label their own dataset scopes and dates.',
  },
  {
    q: 'Is GEX Options financial advice?',
    a: 'No. GEX Options is analytics software. It does not recommend a trade or guarantee an outcome.',
  },
  {
    q: 'When does the trial begin?',
    a: `The current ${trialDays}-day trial begins after checkout is completed. The Pricing page shows the current billing choices and terms before you continue.`,
  },
  {
    q: 'Can I cancel before the trial ends?',
    a: 'Yes. Open the billing portal from your account to cancel before the trial ends and avoid a subscription charge. Otherwise, your selected monthly or yearly subscription starts and renews automatically.',
  },
])

export const featureFaqs = Object.freeze([
  {
    q: 'Can I inspect exact values without relying on hover?',
    a: 'Yes. Charts provide selected readings for pointer, keyboard, and touch users, and complete returned data remains available in tables or details.',
  },
  {
    q: 'What does Live mean in Live Flow and Live Strikes?',
    a: 'Live Flow and Live Strikes show current-session options activity through periodic updates. Update times and market status stay visible alongside the readings.',
  },
  {
    q: 'What should I check when comparing readings?',
    a: 'Match the symbol, expiry timeframe, date, and units. Use the chart controls to inspect a level and compare it with nearby strikes.',
  },
  {
    q: 'Does the Scanner use my dashboard timeframe?',
    a: 'The Scanner has its own filters and timeframes. Dashboard handoffs carry the relevant symbol and wall timeframe when that context exists.',
  },
  {
    q: 'What does the Options Calculator model?',
    a: 'It models long-call or long-put scenarios from the selected contract, pricing input, quantity, underlying scenario, implied volatility, and time assumptions shown in the view.',
  },
])
